/**
 * Route Finder V2 — source-of-truth technician roster.
 * Do not edit inferred values here; update only from dispatcher-provided roster data.
 */

/** @type {import('./technicianProfiles.js').TechnicianProfile[]} */
export const technicians = [
  {
    techName: 'Joshua Harrington',
    aliases: ['Josh Harrington', 'Joshua H', 'Josh'],
    homeBase: {
      address: '25 Stark Ave, Dover, NH',
      town: 'Dover',
      state: 'NH',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Dover', 'Somersworth', 'Rochester', 'South Berwick', 'North Berwick', 'Eliot', 'York'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Primary NH Seacoast technician.',
  },
  {
    techName: 'Dimitri Rovinskinov',
    aliases: ['Dimitri', 'Dmitri', 'Dmitri Rovinskinov'],
    homeBase: {
      address: '8 Lemont Ln, Kittery, ME',
      town: 'Kittery',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Kittery', 'York', 'York Harbor', 'Cape Neddick', 'Ogunquit', 'Wells', 'Eliot', 'South Berwick'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Southern coastal York County.',
  },
  {
    techName: 'Andrew Gregoire',
    aliases: ['Andrew', 'Andy Gregoire'],
    homeBase: {
      address: 'Lenox St, Sanford, ME',
      town: 'Sanford',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Sanford', 'Springvale', 'Alfred', 'Waterboro', 'Lyman', 'Hollis', 'Shapleigh'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Core inland York County coverage.',
  },
  {
    techName: 'Cole Chenard',
    aliases: ['Cole'],
    homeBase: {
      address: 'Cottage St, Sanford, ME',
      town: 'Sanford',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Sanford', 'Wells', 'Kennebunk', 'Arundel', 'Biddeford'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Sanford to coastal York County.',
  },
  {
    techName: 'Shayne McIntyre',
    aliases: ['Shayne'],
    homeBase: {
      address: 'School St, Sanford, ME',
      town: 'Sanford',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Biddeford', 'Saco', 'Old Orchard Beach', 'Scarborough', 'South Portland'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Coastal York/Cumberland border coverage.',
  },
  {
    techName: 'Alex Gray',
    aliases: ['Alex'],
    homeBase: {
      address: 'Cross St, Sanford, ME',
      town: 'Sanford',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Exeter', 'Hampton', 'Seabrook', 'Rye', 'North Hampton', 'Southern NH Seacoast'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Primary NH coastal coverage.',
  },
  {
    techName: 'Jay Glaude',
    aliases: ['Jay'],
    homeBase: {
      address: 'North Ave, Sanford, ME',
      town: 'Sanford',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Wells', 'Ogunquit', 'York', 'Kittery', 'Eliot', 'South Berwick'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Southern York County coastal coverage.',
  },
  {
    techName: 'Joseph Willey',
    aliases: ['Joe Willey', 'Joseph'],
    homeBase: {
      address: '13 Clearbrook Crossing, Kennebunk, ME',
      town: 'Kennebunk',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Kennebunk', 'Kennebunkport', 'Wells', 'Cape Porpoise', 'Arundel'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Kennebunk/Kennebunkport coverage.',
  },
  {
    techName: 'Jack Johnson',
    aliases: ['Jack'],
    homeBase: {
      address: '5 Lady Slipper Ln, Kennebunk, ME',
      town: 'Kennebunk',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Kennebunk', 'Saco', 'Biddeford', 'Old Orchard Beach', 'Scarborough'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Kennebunk to Biddeford/Saco/OOB corridor.',
  },
  {
    techName: 'Justin Giambusso',
    aliases: ['Justin'],
    homeBase: {
      address: '18 Green Ghost Rd, Shapleigh, ME',
      town: 'Shapleigh',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Shapleigh', 'Waterboro', 'Alfred', 'Hollis', 'Buxton', 'Lyman'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Inland western York County.',
  },
  {
    techName: 'Ian Pratt',
    aliases: ['Ian'],
    homeBase: {
      address: '25 Harmon Ave, Old Orchard Beach, ME',
      town: 'Old Orchard Beach',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Scarborough', 'South Portland', 'Cape Elizabeth', 'Old Orchard Beach', 'Saco'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Southern Greater Portland and OOB coverage.',
  },
  {
    techName: 'Patrick Carney',
    aliases: ['Patrick'],
    homeBase: {
      address: '65 Ocean Ave, Old Orchard Beach, ME',
      town: 'Old Orchard Beach',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Old Orchard Beach', 'Saco', 'Biddeford', 'Scarborough', 'Ferry Beach'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'OOB/Biddeford/Saco specialist.',
  },
  {
    techName: 'Paige Bullock',
    aliases: ['Paige'],
    homeBase: {
      address: '112 Blue Spruce Farm Rd, Westbrook, ME',
      town: 'Westbrook',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Westbrook', 'Gorham', 'Windham', 'Buxton', 'Standish'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Inland Cumberland County coverage.',
  },
  {
    techName: 'Chris McGary',
    aliases: ['Chris'],
    homeBase: {
      address: '3 Willis Farm Rd, Gorham, ME',
      town: 'Gorham',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Gorham', 'Windham', 'Standish', 'Buxton', 'Westbrook'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Western Cumberland County coverage.',
  },
  {
    techName: 'Tate Tibbetts',
    aliases: ['Tate'],
    homeBase: {
      address: '62 Coldwater Brook Rd, Oxford, ME',
      town: 'Oxford',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Oxford', 'Norway', 'South Paris', 'Mechanic Falls', 'Poland', 'Gray'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Oxford County coverage.',
  },
  {
    techName: 'Quincy Coachman',
    aliases: ['Quincy'],
    homeBase: {
      address: '18 Union St, Sabattus, ME',
      town: 'Sabattus',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Sabattus', 'Lisbon', 'Topsham', 'Brunswick', 'Bath', 'Wiscasset'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Midcoast gateway coverage.',
  },
  {
    techName: 'Lee Pelletier',
    aliases: ['Lee'],
    homeBase: {
      address: '1144 US-2, Rumford, ME',
      town: 'Rumford',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Rumford', 'Mexico', 'Dixfield', 'Bethel', 'Norway', 'Oxford'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Large rural Western Maine territory. Can usually absorb heavier routing than most technicians.',
  },
  {
    techName: 'Skyler Ruest',
    aliases: ['Skyler', 'Skyler Ruest'],
    homeBase: {
      address: '479 Tuttle Rd, Pownal, ME',
      town: 'Pownal',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Pownal', 'Freeport', 'Durham', 'Yarmouth', 'Brunswick'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Freeport/Yarmouth corridor coverage.',
  },
  {
    techName: 'Michael Caswell',
    aliases: ['Michael', 'Mike Caswell', 'Mike'],
    homeBase: {
      address: '306 Hacker Rd, Brunswick, ME',
      town: 'Brunswick',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Brunswick', 'Topsham', 'Bath', 'Harpswell', 'Freeport'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Brunswick/Topsham/Bath/Harpswell coverage.',
  },
  {
    techName: 'Matthew Lavigne',
    aliases: ['Matthew', 'Matt Lavigne', 'Matt'],
    homeBase: {
      address: '15 Fitzgerald Ave, Lewiston, ME',
      town: 'Lewiston',
      state: 'ME',
      lat: null,
      lng: null,
    },
    normalServiceAreas: ['Lewiston', 'Auburn', 'Lisbon', 'Sabattus', 'Gray', 'Topsham'],
    preferredMaxStops: 13,
    hardMaxStops: 18,
    usualStartTime: '08:30',
    usualEndTime: '17:00',
    canDoServices: ['RIT', 'IQ', 'TICK_MOSQUITO', 'BED_BUG', 'COMMERCIAL', 'RESERVICE', 'FOLLOW_UP', 'GENERAL'],
    cannotDoServices: [],
    handlesCommercial: true,
    handlesBedBugs: true,
    handlesTickMosquito: true,
    handlesRodentWork: true,
    notes: 'Primary Lewiston/Auburn market technician.',
  },
];
