/**
 * Dispatcher-approved Route Finder V2 validation examples (002–051).
 * Example 001 remains in validationExamples.js.
 */

/** @type {import('./validationExamples.js').RouteFinderValidationExample[]} */
export const ADDITIONAL_VALIDATION_EXAMPLES = [
  {
    id: 'kennebunk-iq-example-002',
    date: '2026-06-18',
    newJob: {
      address: '123 Main St, Kennebunk, ME',
      lat: 43.3845,
      lng: -70.5448,
      serviceType: 'IQ',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Joseph Willey',
    acceptedRankMax: 1,
    acceptableTechNames: ['Joseph Willey', 'Jack Johnson'],
    expectedNotTechNames: ['Paige Bullock', 'Ian Pratt'],
    reasonTags: ['same-area', 'kennebunk-cluster', 'lighter-route'],
    dispatcherReason: 'Joseph is the cleaner Kennebunk-area choice and should beat Portland/OOB-area techs.',
    notes: 'Avoid sending Portland-area techs unless no Kennebunk/Saco route is available.',
  },
  {
    id: 'kennebunk-rit-example-003',
    date: '2026-06-18',
    newJob: {
      address: '45 Fletcher St, Kennebunk, ME',
      lat: 43.3902,
      lng: -70.5364,
      serviceType: 'RIT',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Jack Johnson',
    acceptedRankMax: 2,
    acceptableTechNames: ['Jack Johnson', 'Joseph Willey'],
    expectedNotTechNames: ['Paige Bullock', 'Ian Pratt'],
    reasonTags: ['same-area', 'kennebunk-cluster', 'rodent-work'],
    dispatcherReason: 'Jack or Joseph should own this Kennebunk RIT depending on existing route load.',
    notes: 'Do not favor Portland-area techs over Kennebunk-area techs.',
  },
  {
    id: 'wells-iq-example-004',
    date: '2026-06-18',
    newJob: {
      address: '77 Sanford Rd, Wells, ME',
      lat: 43.3223,
      lng: -70.5804,
      serviceType: 'IQ',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Joseph Willey',
    acceptedRankMax: 1,
    acceptableTechNames: ['Joseph Willey', 'Jack Johnson'],
    expectedNotTechNames: ['Paige Bullock', 'Ian Pratt'],
    reasonTags: ['same-area', 'wells-kennebunk-corridor'],
    dispatcherReason: 'Wells should stay with the Kennebunk/Wells corridor techs.',
    notes: 'Avoid routing Wells to Portland/OOB unless local route is overloaded.',
  },
  {
    id: 'wells-tm-example-005',
    date: '2026-06-18',
    newJob: {
      address: '18 Harbor Rd, Wells, ME',
      lat: 43.3059,
      lng: -70.5752,
      serviceType: 'TICK_MOSQUITO',
      timePreference: 'PM',
      exteriorOnly: true,
      isPaidInitial: true,
    },
    expectedTechName: 'Jack Johnson',
    acceptedRankMax: 2,
    acceptableTechNames: ['Jack Johnson', 'Joseph Willey'],
    expectedNotTechNames: ['Paige Bullock', 'Ian Pratt'],
    reasonTags: ['same-area', 'exterior-only', 'southern-york-county'],
    dispatcherReason: 'Jack or Joseph should be favored for Wells exterior tick and mosquito work.',
    notes: 'PM preference should not override strong same-region fit unless route timing is impossible.',
  },
  {
    id: 'sanford-iq-example-006',
    date: '2026-06-18',
    newJob: {
      address: '25 Main St, Sanford, ME',
      lat: 43.4393,
      lng: -70.7742,
      serviceType: 'IQ',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Andrew Gregoire',
    acceptedRankMax: 2,
    acceptableTechNames: ['Andrew Gregoire', 'Cole Chenard', 'Shayne McIntyre', 'Alex Gray'],
    expectedNotTechNames: ['Paige Bullock', 'Ian Pratt'],
    reasonTags: ['same-town', 'sanford-cluster'],
    dispatcherReason: 'Sanford jobs should stay with Sanford-based technicians.',
    notes: 'Avoid pulling techs from Portland/OOB when several Sanford techs are available.',
  },
  {
    id: 'sanford-general-example-007',
    date: '2026-06-18',
    newJob: {
      address: '14 Lebanon St, Sanford, ME',
      lat: 43.4415,
      lng: -70.7778,
      serviceType: 'GENERAL',
      timePreference: 'AM',
      isPaidInitial: true,
    },
    expectedTechName: 'Cole Chenard',
    acceptedRankMax: 2,
    acceptableTechNames: ['Cole Chenard', 'Andrew Gregoire', 'Shayne McIntyre', 'Alex Gray'],
    expectedNotTechNames: ['Paige Bullock', 'Ian Pratt'],
    reasonTags: ['same-town', 'sanford-cluster', 'am-window'],
    dispatcherReason: 'Cole is a strong Sanford-area fit and should beat out-of-region techs.',
    notes: 'AM window should still prioritize Sanford cluster first.',
  },
  {
    id: 'sanford-rit-example-008',
    date: '2026-06-18',
    newJob: {
      address: '91 High St, Sanford, ME',
      lat: 43.4348,
      lng: -70.7689,
      serviceType: 'RIT',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Shayne McIntyre',
    acceptedRankMax: 2,
    acceptableTechNames: ['Shayne McIntyre', 'Andrew Gregoire', 'Cole Chenard', 'Alex Gray'],
    expectedNotTechNames: ['Paige Bullock', 'Ian Pratt'],
    reasonTags: ['same-town', 'sanford-cluster', 'rodent-work'],
    dispatcherReason: 'Sanford RIT should remain with a Sanford technician unless all are overloaded.',
    notes: 'Rodent work is supported by the Sanford tech cluster.',
  },
  {
    id: 'sanford-bedbug-example-009',
    date: '2026-06-18',
    newJob: {
      address: '8 School St, Sanford, ME',
      lat: 43.4381,
      lng: -70.7735,
      serviceType: 'BED_BUG',
      timePreference: '12-4',
      customerMustBeHome: true,
      isPaidInitial: true,
    },
    expectedTechName: 'Alex Gray',
    acceptedRankMax: 2,
    acceptableTechNames: ['Alex Gray', 'Andrew Gregoire', 'Cole Chenard', 'Shayne McIntyre'],
    expectedNotTechNames: ['Paige Bullock', 'Ian Pratt'],
    reasonTags: ['same-town', 'bed-bug', 'customer-home-required'],
    dispatcherReason: 'A Sanford bed bug job should stay with a capable Sanford tech.',
    notes: 'Customer must be home, so time window matters, but region fit should remain important.',
  },
  {
    id: 'shapleigh-rit-example-010',
    date: '2026-06-18',
    newJob: {
      address: '20 Shapleigh Corner Rd, Shapleigh, ME',
      lat: 43.5834,
      lng: -70.8478,
      serviceType: 'RIT',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Justin Giambusso',
    acceptedRankMax: 1,
    acceptableTechNames: ['Justin Giambusso'],
    expectedNotTechNames: ['Paige Bullock', 'Ian Pratt'],
    reasonTags: ['same-area', 'shapleigh-home-base', 'rural-route'],
    dispatcherReason: 'Justin is the strongest Shapleigh-area option.',
    notes: 'This should not be treated as a Portland/OOB job.',
  },
  {
    id: 'alfred-iq-example-011',
    date: '2026-06-18',
    newJob: {
      address: '5 Saco Rd, Alfred, ME',
      lat: 43.4762,
      lng: -70.7184,
      serviceType: 'IQ',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Andrew Gregoire',
    acceptedRankMax: 2,
    acceptableTechNames: ['Andrew Gregoire', 'Cole Chenard', 'Shayne McIntyre'],
    expectedNotTechNames: ['Paige Bullock'],
    reasonTags: ['sanford-region', 'nearby-town'],
    dispatcherReason: 'Alfred should usually be handled by the Sanford cluster.',
    notes: 'Do not over-prefer Greater Portland for Alfred.',
  },
  {
    id: 'old-orchard-iq-example-012',
    date: '2026-06-18',
    newJob: {
      address: '12 Old Orchard St, Old Orchard Beach, ME',
      lat: 43.5172,
      lng: -70.3779,
      serviceType: 'IQ',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Ian Pratt',
    acceptedRankMax: 1,
    acceptableTechNames: ['Ian Pratt', 'Patrick Carney'],
    expectedNotTechNames: ['Joseph Willey', 'Paige Bullock'],
    reasonTags: ['same-town', 'oob-cluster'],
    dispatcherReason: 'Old Orchard Beach should favor Ian or Patrick.',
    notes: 'Do not send Kennebunk or Portland techs when OOB techs are available.',
  },
  {
    id: 'old-orchard-tm-example-013',
    date: '2026-06-18',
    newJob: {
      address: '30 Ocean Park Rd, Old Orchard Beach, ME',
      lat: 43.5041,
      lng: -70.3955,
      serviceType: 'TICK_MOSQUITO',
      timePreference: 'PM',
      exteriorOnly: true,
      isPaidInitial: true,
    },
    expectedTechName: 'Patrick Carney',
    acceptedRankMax: 2,
    acceptableTechNames: ['Patrick Carney', 'Ian Pratt'],
    expectedNotTechNames: ['Joseph Willey', 'Paige Bullock'],
    reasonTags: ['same-town', 'oob-cluster', 'exterior-only'],
    dispatcherReason: 'Patrick or Ian should handle Old Orchard exterior routes.',
    notes: 'Exterior-only makes timing more flexible, but same-town fit should still dominate.',
  },
  {
    id: 'saco-general-example-014',
    date: '2026-06-18',
    newJob: {
      address: '55 Main St, Saco, ME',
      lat: 43.5009,
      lng: -70.4428,
      serviceType: 'GENERAL',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Ian Pratt',
    acceptedRankMax: 2,
    acceptableTechNames: ['Ian Pratt', 'Patrick Carney'],
    expectedNotTechNames: ['Joseph Willey', 'Skyler Ruest'],
    reasonTags: ['saco-oob-corridor', 'nearby-route'],
    dispatcherReason: 'Saco should generally route with OOB/Biddeford-area techs.',
    notes: 'Avoid sending Midcoast or Kennebunk techs unless route load requires it.',
  },
  {
    id: 'saco-commercial-example-015',
    date: '2026-06-18',
    newJob: {
      address: '110 Industrial Park Rd, Saco, ME',
      lat: 43.5331,
      lng: -70.4452,
      serviceType: 'COMMERCIAL',
      timePreference: '8-12',
      customerMustBeHome: true,
      isCommercial: true,
      isPaidInitial: true,
    },
    expectedTechName: 'Patrick Carney',
    acceptedRankMax: 2,
    acceptableTechNames: ['Patrick Carney', 'Ian Pratt'],
    expectedNotTechNames: ['Joseph Willey', 'Skyler Ruest'],
    reasonTags: ['commercial', 'saco-oob-corridor', 'morning-window'],
    dispatcherReason: 'Patrick or Ian should be favored for Saco commercial work.',
    notes: 'Morning window should not cause a far-away tech to win unless local techs cannot fit it.',
  },
  {
    id: 'scarborough-iq-example-016',
    date: '2026-06-18',
    newJob: {
      address: '220 US Route 1, Scarborough, ME',
      lat: 43.5781,
      lng: -70.3229,
      serviceType: 'IQ',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Paige Bullock',
    acceptedRankMax: 1,
    acceptableTechNames: ['Paige Bullock'],
    expectedNotTechNames: ['Joseph Willey', 'Lee Pelletier'],
    reasonTags: ['greater-portland', 'same-region'],
    dispatcherReason: 'Scarborough should favor Paige from the Greater Portland cluster.',
    notes: 'Avoid Western Maine or Kennebunk techs for Scarborough unless needed.',
  },
  {
    id: 'scarborough-tm-example-017',
    date: '2026-06-18',
    newJob: {
      address: '8 Black Point Rd, Scarborough, ME',
      lat: 43.5471,
      lng: -70.3197,
      serviceType: 'TICK_MOSQUITO',
      timePreference: 'Anytime',
      exteriorOnly: true,
      isPaidInitial: true,
    },
    expectedTechName: 'Paige Bullock',
    acceptedRankMax: 1,
    acceptableTechNames: ['Paige Bullock'],
    expectedNotTechNames: ['Joseph Willey', 'Tate Tibbetts'],
    reasonTags: ['greater-portland', 'exterior-only'],
    dispatcherReason: 'Paige is the correct Greater Portland-area tech for Scarborough T/M.',
    notes: 'Exterior-only should not weaken the territory match too much.',
  },
  {
    id: 'gorham-rit-example-018',
    date: '2026-06-18',
    newJob: {
      address: '44 Main St, Gorham, ME',
      lat: 43.6795,
      lng: -70.4448,
      serviceType: 'RIT',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Chris McGary',
    acceptedRankMax: 1,
    acceptableTechNames: ['Chris McGary'],
    expectedNotTechNames: ['Joseph Willey', 'Ian Pratt'],
    reasonTags: ['same-town', 'gorham-westbrook-cluster', 'rodent-work'],
    dispatcherReason: 'Chris is the strongest Gorham-area fit.',
    notes: 'Do not send coastal York County techs to Gorham unless no local route is available.',
  },
  {
    id: 'gorham-iq-example-019',
    date: '2026-06-18',
    newJob: {
      address: '19 New Portland Rd, Gorham, ME',
      lat: 43.6827,
      lng: -70.4586,
      serviceType: 'IQ',
      timePreference: '10-12',
      customerMustBeHome: true,
      isPaidInitial: true,
    },
    expectedTechName: 'Chris McGary',
    acceptedRankMax: 1,
    acceptableTechNames: ['Chris McGary'],
    expectedNotTechNames: ['Joseph Willey', 'Ian Pratt'],
    reasonTags: ['same-town', 'time-window', 'gorham-cluster'],
    dispatcherReason: 'Chris should win Gorham IQ even with a tighter window if route can support it.',
    notes: 'Customer must be home, so window feasibility should be considered.',
  },
  {
    id: 'westbrook-general-example-020',
    date: '2026-06-18',
    newJob: {
      address: '100 Main St, Westbrook, ME',
      lat: 43.6770,
      lng: -70.3712,
      serviceType: 'GENERAL',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Paige Bullock',
    acceptedRankMax: 1,
    acceptableTechNames: ['Paige Bullock', 'Chris McGary'],
    expectedNotTechNames: ['Joseph Willey', 'Lee Pelletier'],
    reasonTags: ['same-town', 'greater-portland'],
    dispatcherReason: 'Paige should usually own Westbrook, with Chris as an acceptable nearby option.',
    notes: 'Western Maine techs should not beat Greater Portland techs here.',
  },
  {
    id: 'portland-commercial-example-021',
    date: '2026-06-18',
    newJob: {
      address: '1 Commercial St, Portland, ME',
      lat: 43.6562,
      lng: -70.2504,
      serviceType: 'COMMERCIAL',
      timePreference: '8-12',
      customerMustBeHome: true,
      isCommercial: true,
      isPaidInitial: true,
    },
    expectedTechName: 'Paige Bullock',
    acceptedRankMax: 2,
    acceptableTechNames: ['Paige Bullock', 'Chris McGary'],
    expectedNotTechNames: ['Joseph Willey', 'Lee Pelletier'],
    reasonTags: ['commercial', 'greater-portland', 'morning-window'],
    dispatcherReason: 'Portland commercial work should favor Greater Portland techs.',
    notes: 'Avoid far western or southern York County routes unless necessary.',
  },
  {
    id: 'south-portland-iq-example-022',
    date: '2026-06-18',
    newJob: {
      address: '50 Broadway, South Portland, ME',
      lat: 43.6415,
      lng: -70.2409,
      serviceType: 'IQ',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Paige Bullock',
    acceptedRankMax: 1,
    acceptableTechNames: ['Paige Bullock'],
    expectedNotTechNames: ['Joseph Willey', 'Tate Tibbetts'],
    reasonTags: ['greater-portland', 'same-region'],
    dispatcherReason: 'South Portland should stay with Greater Portland routing.',
    notes: 'Do not let long-distance techs win on base score alone.',
  },
  {
    id: 'cape-elizabeth-tm-example-023',
    date: '2026-06-18',
    newJob: {
      address: '12 Shore Rd, Cape Elizabeth, ME',
      lat: 43.5637,
      lng: -70.2003,
      serviceType: 'TICK_MOSQUITO',
      timePreference: 'Anytime',
      exteriorOnly: true,
      isPaidInitial: true,
    },
    expectedTechName: 'Paige Bullock',
    acceptedRankMax: 1,
    acceptableTechNames: ['Paige Bullock'],
    expectedNotTechNames: ['Joseph Willey', 'Lee Pelletier'],
    reasonTags: ['greater-portland', 'coastal-portland', 'exterior-only'],
    dispatcherReason: 'Cape Elizabeth should route with Paige as the Portland-area tech.',
    notes: 'Avoid sending Kennebunk or Western Maine techs.',
  },
  {
    id: 'windham-general-example-024',
    date: '2026-06-18',
    newJob: {
      address: '770 Roosevelt Trail, Windham, ME',
      lat: 43.8370,
      lng: -70.4387,
      serviceType: 'GENERAL',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Chris McGary',
    acceptedRankMax: 2,
    acceptableTechNames: ['Chris McGary', 'Paige Bullock'],
    expectedNotTechNames: ['Joseph Willey', 'Ian Pratt'],
    reasonTags: ['gorham-westbrook-cluster', 'same-region'],
    dispatcherReason: 'Windham should favor Chris or Paige, not coastal York County.',
    notes: 'Accept Paige if route density is stronger, but Chris should be highly competitive.',
  },
  {
    id: 'standish-rit-example-025',
    date: '2026-06-18',
    newJob: {
      address: '35 Ossipee Trail W, Standish, ME',
      lat: 43.7350,
      lng: -70.5511,
      serviceType: 'RIT',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Chris McGary',
    acceptedRankMax: 1,
    acceptableTechNames: ['Chris McGary'],
    expectedNotTechNames: ['Joseph Willey', 'Ian Pratt'],
    reasonTags: ['same-region', 'rural-west-portland', 'rodent-work'],
    dispatcherReason: 'Standish should stay with Chris\'s Gorham/Standish corridor.',
    notes: 'Do not route Standish from coastal York County unless route load requires it.',
  },
  {
    id: 'oxford-iq-example-026',
    date: '2026-06-18',
    newJob: {
      address: '160 Main St, Oxford, ME',
      lat: 44.1317,
      lng: -70.4934,
      serviceType: 'IQ',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Tate Tibbetts',
    acceptedRankMax: 1,
    acceptableTechNames: ['Tate Tibbetts'],
    expectedNotTechNames: ['Paige Bullock', 'Joseph Willey'],
    reasonTags: ['same-town', 'western-maine'],
    dispatcherReason: 'Oxford should strongly favor Tate.',
    notes: 'Greater Portland techs should not beat the Oxford-area tech.',
  },
  {
    id: 'norway-general-example-027',
    date: '2026-06-18',
    newJob: {
      address: '10 Main St, Norway, ME',
      lat: 44.2139,
      lng: -70.5448,
      serviceType: 'GENERAL',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Tate Tibbetts',
    acceptedRankMax: 1,
    acceptableTechNames: ['Tate Tibbetts'],
    expectedNotTechNames: ['Paige Bullock', 'Joseph Willey'],
    reasonTags: ['western-maine', 'nearby-town'],
    dispatcherReason: 'Norway belongs with the Oxford/Western Maine route.',
    notes: 'Do not allow Portland-area techs to rank above Tate here.',
  },
  {
    id: 'paris-rit-example-028',
    date: '2026-06-18',
    newJob: {
      address: '25 Market Square, Paris, ME',
      lat: 44.2598,
      lng: -70.5009,
      serviceType: 'RIT',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Tate Tibbetts',
    acceptedRankMax: 1,
    acceptableTechNames: ['Tate Tibbetts'],
    expectedNotTechNames: ['Paige Bullock', 'Joseph Willey'],
    reasonTags: ['western-maine', 'rodent-work'],
    dispatcherReason: 'Paris RIT should route with Tate\'s Oxford-area coverage.',
    notes: 'Western Maine territory should dominate this recommendation.',
  },
  {
    id: 'rumford-iq-example-029',
    date: '2026-06-18',
    newJob: {
      address: '85 Congress St, Rumford, ME',
      lat: 44.5537,
      lng: -70.5509,
      serviceType: 'IQ',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Lee Pelletier',
    acceptedRankMax: 1,
    acceptableTechNames: ['Lee Pelletier'],
    expectedNotTechNames: ['Paige Bullock', 'Joseph Willey'],
    reasonTags: ['same-town', 'rumford-region', 'western-maine'],
    dispatcherReason: 'Rumford should strongly favor Lee.',
    notes: 'Do not send Greater Portland or York County techs to Rumford unless absolutely necessary.',
  },
  {
    id: 'mexico-general-example-030',
    date: '2026-06-18',
    newJob: {
      address: '20 Main St, Mexico, ME',
      lat: 44.5602,
      lng: -70.5457,
      serviceType: 'GENERAL',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Lee Pelletier',
    acceptedRankMax: 1,
    acceptableTechNames: ['Lee Pelletier'],
    expectedNotTechNames: ['Paige Bullock', 'Joseph Willey'],
    reasonTags: ['rumford-region', 'nearby-town'],
    dispatcherReason: 'Mexico should route with Lee because it is part of the Rumford pocket.',
    notes: 'Strong local-region fit should beat any generic score advantage.',
  },
  {
    id: 'bethel-rit-example-031',
    date: '2026-06-18',
    newJob: {
      address: '9 Main St, Bethel, ME',
      lat: 44.4042,
      lng: -70.7906,
      serviceType: 'RIT',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Lee Pelletier',
    acceptedRankMax: 1,
    acceptableTechNames: ['Lee Pelletier'],
    expectedNotTechNames: ['Paige Bullock', 'Joseph Willey'],
    reasonTags: ['western-maine', 'rural-route', 'rodent-work'],
    dispatcherReason: 'Bethel should stay with the western route structure.',
    notes: 'Avoid far-away Greater Portland or York County techs.',
  },
  {
    id: 'auburn-iq-example-032',
    date: '2026-06-18',
    newJob: {
      address: '100 Center St, Auburn, ME',
      lat: 44.0979,
      lng: -70.2312,
      serviceType: 'IQ',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Matthew Lavigne',
    acceptedRankMax: 2,
    acceptableTechNames: ['Matthew Lavigne', 'Quincy Coachman'],
    expectedNotTechNames: ['Paige Bullock', 'Joseph Willey'],
    reasonTags: ['lewiston-auburn', 'same-region'],
    dispatcherReason: 'Auburn should favor Matthew, with Quincy as nearby backup.',
    notes: 'Do not route Auburn from Portland if local central Maine options exist.',
  },
  {
    id: 'lewiston-general-example-033',
    date: '2026-06-18',
    newJob: {
      address: '50 Lisbon St, Lewiston, ME',
      lat: 44.0965,
      lng: -70.2148,
      serviceType: 'GENERAL',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Matthew Lavigne',
    acceptedRankMax: 1,
    acceptableTechNames: ['Matthew Lavigne'],
    expectedNotTechNames: ['Paige Bullock', 'Joseph Willey'],
    reasonTags: ['same-town', 'lewiston-auburn'],
    dispatcherReason: 'Lewiston should strongly favor Matthew.',
    notes: 'Same-town tech should beat outside-area techs.',
  },
  {
    id: 'sabattus-iq-example-034',
    date: '2026-06-18',
    newJob: {
      address: '20 Main St, Sabattus, ME',
      lat: 44.1198,
      lng: -70.1064,
      serviceType: 'IQ',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Quincy Coachman',
    acceptedRankMax: 2,
    acceptableTechNames: ['Quincy Coachman', 'Matthew Lavigne'],
    expectedNotTechNames: ['Paige Bullock', 'Joseph Willey'],
    reasonTags: ['same-town', 'central-maine'],
    dispatcherReason: 'Sabattus should favor Quincy, with Matthew as acceptable backup.',
    notes: 'Avoid Portland/York County techs for Sabattus.',
  },
  {
    id: 'lisbon-general-example-035',
    date: '2026-06-18',
    newJob: {
      address: '10 Main St, Lisbon, ME',
      lat: 44.0317,
      lng: -70.1045,
      serviceType: 'GENERAL',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Matthew Lavigne',
    acceptedRankMax: 2,
    acceptableTechNames: ['Matthew Lavigne', 'Michael Caswell', 'Quincy Coachman'],
    expectedNotTechNames: ['Paige Bullock', 'Joseph Willey'],
    reasonTags: ['central-maine', 'lewiston-brunswick-bridge'],
    dispatcherReason: 'Lisbon can go Matthew, Michael, or Quincy depending on route density.',
    notes: 'This is a bridge-town example where acceptedRankMax should allow some flexibility.',
  },
  {
    id: 'topsham-iq-example-036',
    date: '2026-06-18',
    newJob: {
      address: '65 Topsham Fair Mall Rd, Topsham, ME',
      lat: 43.9277,
      lng: -69.9738,
      serviceType: 'IQ',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Michael Caswell',
    acceptedRankMax: 1,
    acceptableTechNames: ['Michael Caswell'],
    expectedNotTechNames: ['Paige Bullock', 'Joseph Willey'],
    reasonTags: ['same-region', 'brunswick-topsham'],
    dispatcherReason: 'Topsham should favor Michael from the Brunswick/Topsham route.',
    notes: 'Do not send Greater Portland or York County techs here over Michael.',
  },
  {
    id: 'brunswick-general-example-037',
    date: '2026-06-18',
    newJob: {
      address: '150 Maine St, Brunswick, ME',
      lat: 43.9140,
      lng: -69.9653,
      serviceType: 'GENERAL',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Michael Caswell',
    acceptedRankMax: 1,
    acceptableTechNames: ['Michael Caswell'],
    expectedNotTechNames: ['Paige Bullock', 'Joseph Willey'],
    reasonTags: ['same-town', 'brunswick-topsham'],
    dispatcherReason: 'Brunswick should strongly favor Michael.',
    notes: 'Same-town fit should be decisive.',
  },
  {
    id: 'harpswell-tm-example-038',
    date: '2026-06-18',
    newJob: {
      address: '20 Harpswell Neck Rd, Harpswell, ME',
      lat: 43.8017,
      lng: -69.9843,
      serviceType: 'TICK_MOSQUITO',
      timePreference: 'Anytime',
      exteriorOnly: true,
      isPaidInitial: true,
    },
    expectedTechName: 'Michael Caswell',
    acceptedRankMax: 1,
    acceptableTechNames: ['Michael Caswell'],
    expectedNotTechNames: ['Paige Bullock', 'Joseph Willey'],
    reasonTags: ['midcoast', 'exterior-only', 'brunswick-region'],
    dispatcherReason: 'Harpswell should route with Michael from the Brunswick/Midcoast area.',
    notes: 'Avoid assigning this to Portland unless no midcoast route exists.',
  },
  {
    id: 'freeport-iq-example-039',
    date: '2026-06-18',
    newJob: {
      address: '35 Main St, Freeport, ME',
      lat: 43.8570,
      lng: -70.1031,
      serviceType: 'IQ',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Skyler Ruest',
    acceptedRankMax: 2,
    acceptableTechNames: ['Skyler Ruest', 'Michael Caswell'],
    expectedNotTechNames: ['Joseph Willey', 'Lee Pelletier'],
    reasonTags: ['freeport-yarmouth-corridor', 'same-region'],
    dispatcherReason: 'Freeport should favor Skyler, with Michael as acceptable backup.',
    notes: 'Do not route Freeport from York County or Western Maine.',
  },
  {
    id: 'yarmouth-general-example-040',
    date: '2026-06-18',
    newJob: {
      address: '20 Main St, Yarmouth, ME',
      lat: 43.8006,
      lng: -70.1867,
      serviceType: 'GENERAL',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Skyler Ruest',
    acceptedRankMax: 2,
    acceptableTechNames: ['Skyler Ruest', 'Paige Bullock'],
    expectedNotTechNames: ['Joseph Willey', 'Lee Pelletier'],
    reasonTags: ['freeport-yarmouth-corridor', 'greater-portland-edge'],
    dispatcherReason: 'Yarmouth should favor Skyler, with Paige acceptable if route density is stronger.',
    notes: 'This tests corridor flexibility without allowing far-away techs to win.',
  },
  {
    id: 'durham-rit-example-041',
    date: '2026-06-18',
    newJob: {
      address: '15 Royalsborough Rd, Durham, ME',
      lat: 43.9706,
      lng: -70.1227,
      serviceType: 'RIT',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Skyler Ruest',
    acceptedRankMax: 1,
    acceptableTechNames: ['Skyler Ruest'],
    expectedNotTechNames: ['Joseph Willey', 'Paige Bullock'],
    reasonTags: ['same-region', 'freeport-durham-corridor', 'rodent-work'],
    dispatcherReason: 'Durham should stay with Skyler\'s Pownal/Freeport/Durham territory.',
    notes: 'Do not route this from coastal York County.',
  },
  {
    id: 'dover-iq-example-042',
    date: '2026-06-18',
    newJob: {
      address: '100 Central Ave, Dover, NH',
      lat: 43.1979,
      lng: -70.8737,
      serviceType: 'IQ',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Joshua Harrington',
    acceptedRankMax: 1,
    acceptableTechNames: ['Joshua Harrington'],
    expectedNotTechNames: ['Joseph Willey', 'Paige Bullock'],
    reasonTags: ['same-town', 'seacoast-nh'],
    dispatcherReason: 'Dover should strongly favor Joshua.',
    notes: 'Do not send Maine coastal techs if Joshua is available.',
  },
  {
    id: 'rochester-general-example-043',
    date: '2026-06-18',
    newJob: {
      address: '15 Wakefield St, Rochester, NH',
      lat: 43.3045,
      lng: -70.9756,
      serviceType: 'GENERAL',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Joshua Harrington',
    acceptedRankMax: 1,
    acceptableTechNames: ['Joshua Harrington'],
    expectedNotTechNames: ['Paige Bullock', 'Joseph Willey'],
    reasonTags: ['seacoast-nh', 'dover-rochester-corridor'],
    dispatcherReason: 'Rochester should route with Joshua from the Dover/Rochester corridor.',
    notes: 'Maine techs should not outrank the NH route owner.',
  },
  {
    id: 'somersworth-rit-example-044',
    date: '2026-06-18',
    newJob: {
      address: '30 High St, Somersworth, NH',
      lat: 43.2617,
      lng: -70.8653,
      serviceType: 'RIT',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Joshua Harrington',
    acceptedRankMax: 1,
    acceptableTechNames: ['Joshua Harrington'],
    expectedNotTechNames: ['Paige Bullock', 'Joseph Willey'],
    reasonTags: ['seacoast-nh', 'rodent-work', 'same-region'],
    dispatcherReason: 'Somersworth should favor Joshua as the nearby NH technician.',
    notes: 'Avoid sending Maine techs over Joshua.',
  },
  {
    id: 'portsmouth-commercial-example-045',
    date: '2026-06-18',
    newJob: {
      address: '100 Market St, Portsmouth, NH',
      lat: 43.0780,
      lng: -70.7577,
      serviceType: 'COMMERCIAL',
      timePreference: '8-12',
      customerMustBeHome: true,
      isCommercial: true,
      isPaidInitial: true,
    },
    expectedTechName: 'Dmitri Rovinskinov',
    acceptedRankMax: 1,
    acceptableTechNames: ['Dmitri Rovinskinov'],
    expectedNotTechNames: ['Paige Bullock', 'Ian Pratt'],
    reasonTags: ['seacoast-nh', 'commercial', 'kittery-portsmouth'],
    dispatcherReason: 'Portsmouth commercial work should favor Dmitri from the Kittery/Seacoast area.',
    notes: 'Do not send Portland/OOB techs unless seacoast tech is unavailable.',
  },
  {
    id: 'kittery-iq-example-046',
    date: '2026-06-18',
    newJob: {
      address: '10 Walker St, Kittery, ME',
      lat: 43.0881,
      lng: -70.7362,
      serviceType: 'IQ',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Dmitri Rovinskinov',
    acceptedRankMax: 1,
    acceptableTechNames: ['Dmitri Rovinskinov'],
    expectedNotTechNames: ['Paige Bullock', 'Ian Pratt'],
    reasonTags: ['same-town', 'seacoast-maine'],
    dispatcherReason: 'Kittery should strongly favor Dmitri.',
    notes: 'Same-town/home-base logic should win.',
  },
  {
    id: 'york-general-example-047',
    date: '2026-06-18',
    newJob: {
      address: '1 York St, York, ME',
      lat: 43.1436,
      lng: -70.6514,
      serviceType: 'GENERAL',
      timePreference: 'Anytime',
      isPaidInitial: true,
    },
    expectedTechName: 'Dmitri Rovinskinov',
    acceptedRankMax: 2,
    acceptableTechNames: ['Dmitri Rovinskinov', 'Joseph Willey'],
    expectedNotTechNames: ['Paige Bullock', 'Ian Pratt'],
    reasonTags: ['seacoast-maine', 'york-kittery-corridor'],
    dispatcherReason: 'York should favor Dmitri, with Joseph acceptable depending on southern York County route density.',
    notes: 'Portland/OOB techs should not win here.',
  },
  {
    id: 'biddeford-reservice-example-048',
    date: '2026-06-18',
    newJob: {
      address: '25 Alfred St, Biddeford, ME',
      lat: 43.4926,
      lng: -70.4534,
      serviceType: 'RESERVICE',
      timePreference: 'Anytime',
      isReservice: true,
    },
    expectedTechName: 'Ian Pratt',
    acceptedRankMax: 2,
    acceptableTechNames: ['Ian Pratt', 'Patrick Carney'],
    expectedNotTechNames: ['Joseph Willey', 'Skyler Ruest'],
    reasonTags: ['reservice', 'same-route', 'saco-biddeford-oob'],
    dispatcherReason: 'Biddeford reservice should stay with the OOB/Saco route when possible.',
    notes: 'Reservice should favor route familiarity and nearby stops.',
  },
  {
    id: 'portland-followup-example-049',
    date: '2026-06-18',
    newJob: {
      address: '22 Forest Ave, Portland, ME',
      lat: 43.6605,
      lng: -70.2657,
      serviceType: 'FOLLOW_UP',
      timePreference: '12-4',
      customerMustBeHome: true,
    },
    expectedTechName: 'Paige Bullock',
    acceptedRankMax: 1,
    acceptableTechNames: ['Paige Bullock'],
    expectedNotTechNames: ['Joseph Willey', 'Lee Pelletier'],
    reasonTags: ['follow-up', 'greater-portland', 'time-window'],
    dispatcherReason: 'Portland follow-up should stay with Paige when the route can support the window.',
    notes: 'Customer must be home, so window fit matters.',
  },
  {
    id: 'kennebunk-commercial-example-050',
    date: '2026-06-18',
    newJob: {
      address: '70 Portland Rd, Kennebunk, ME',
      lat: 43.4014,
      lng: -70.5310,
      serviceType: 'COMMERCIAL',
      timePreference: 'Anytime',
      isCommercial: true,
      isPaidInitial: true,
    },
    expectedTechName: 'Joseph Willey',
    acceptedRankMax: 2,
    acceptableTechNames: ['Joseph Willey', 'Jack Johnson'],
    expectedNotTechNames: ['Paige Bullock', 'Ian Pratt'],
    reasonTags: ['commercial', 'kennebunk-cluster', 'same-area'],
    dispatcherReason: 'Kennebunk commercial work should favor Joseph or Jack.',
    notes: 'Commercial capability matters, but territory fit should remain decisive.',
  },
  {
    id: 'old-orchard-bedbug-example-051',
    date: '2026-06-18',
    newJob: {
      address: '9 East Grand Ave, Old Orchard Beach, ME',
      lat: 43.5160,
      lng: -70.3722,
      serviceType: 'BED_BUG',
      timePreference: '8-12',
      customerMustBeHome: true,
      isPaidInitial: true,
    },
    expectedTechName: 'Ian Pratt',
    acceptedRankMax: 2,
    acceptableTechNames: ['Ian Pratt', 'Patrick Carney'],
    expectedNotTechNames: ['Joseph Willey', 'Paige Bullock'],
    reasonTags: ['bed-bug', 'oob-cluster', 'customer-home-required'],
    dispatcherReason: 'Old Orchard bed bug work should favor Ian or Patrick.',
    notes: 'Morning window matters, but OOB territory match should remain strong.',
  },
];
